name: Deploy JavaScript Playground

on:
  push:
    branches: [main]
    paths:
      - 'javascript/playground/**'

env:
  PLAYGROUND: javascript/playground

permissions:
  contents: write

jobs:   
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'
          cache-dependency-path: ${{ env.PLAYGROUND }}/package-lock.json

      - name: Install dependencies then run 'build'
        working-directory: ${{ env.PLAYGROUND }}
        run: |
          npm ci --omit=dev
          npm run build

      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ env.PLAYGROUND }}/dist
          target-folder: javascript
          branch: gh-pages
          clean: false
