name: Deploy JS Playground

on:
    push:
        branches: [main]
        paths:
            - "javascript/.playground/**"

permissions:
    contents: write

defaults:
    run:
        working-directory: ./javascript/.playground

jobs:
    deploy:
        runs-on: ubuntu-latest
	if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v4

            - name: Install + Build
              run: |
                  npm install
                  npm run build

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: javascript/.playground/dist
                  target-folder: javascript
                  branch: gh-pages
                  clean: false
